<div class="panel panel-default" style="width: 95%; margin-left:2.5%;">
	<div class="panel-heading">
		<h3 class="panel-title text-center">Exame de Graduação</h3>
	</div>
	<div class="panel-body  filter-content">
		<div class="row">
			<div class="col-md-3">
				<div class="thumbnail">
					<img src="<?php echo $this->baseUrl(); ?>/img/faixacinza.png" onclick="window.location.href='<?php echo $this->baseUrl(); ?>/exame/geraexame?faixa=Cinza&nivTec=1'" class="faixa" />
					<div class="caption">
						<h5 class="text-center"> Exame Graduação Cinza </h5>
					</div>
				</div>
			</div>
			<div class="col-md-3">
					<div class="thumbnail">
					<img src="<?php echo $this->baseUrl(); ?>/img/faixaazul.png" class="faixa" onClick="window.location.href='<?php echo $this->baseUrl(); ?>/exame/geraexame?faixa=Azul&nivTec=2'"/>
					<div class="caption">
						<h5 class="text-center"> Exame Graduação Azul </h5>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="thumbnail">
					<img src="<?php echo $this->baseUrl(); ?>/img/faixaamarela.png" class="faixa" onClick="window.location.href='<?php echo $this->baseUrl(); ?>/exame/geraexame?faixa=Amarela&nivTec=3'"/>
					<div class="caption">
						<h5 class="text-center"> Exame Graduação Amarela </h5>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="thumbnail">
					<img src="<?php echo $this->baseUrl(); ?>/img/faixalaranja.png" class="faixa" onClick="window.location.href='<?php echo $this->baseUrl(); ?>/exame/geraexame?faixa=Laranja&nivTec=4'"/>
					<div class="caption">
						<h5 class="text-center"> Exame Graduação Laranja </h5>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3">
				<div class="thumbnail">
					<img src="<?php echo $this->baseUrl(); ?>/img/faixaverde.png" class="faixa" onClick="window.location.href='<?php echo $this->baseUrl(); ?>/exame/geraexame?faixa=Verde&nivTec=5'"/>
					<div class="caption">
						<h5 class="text-center"> Exame Graduação Verde </h5>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="thumbnail">
					<img src="<?php echo $this->baseUrl(); ?>/img/faixaroxa.png" class="faixa" onClick="window.location.href='<?php echo $this->baseUrl(); ?>/exame/geraexame?faixa=Roxa&nivTec=6'"/>
					<div class="caption">
						<h5 class="text-center"> Exame Graduação Roxa </h5>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="thumbnail">
					<img src="<?php echo $this->baseUrl(); ?>/img/faixamarrom.png" class="faixa" onClick="window.location.href='<?php echo $this->baseUrl(); ?>/exame/geraexame?faixa=Marrom&nivTec=7'"/>
					<div class="caption">
						<h5 class="text-center"> Exame Graduação Marrom </h5>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="thumbnail">
					<img src="<?php echo $this->baseUrl(); ?>/img/faixapreta.png" class="faixa" onClick="window.location.href='<?php echo $this->baseUrl(); ?>/exame/geraexame?faixa=Preta&nivTec=8'"/>
					<div class="caption">
						<h5 class="text-center"> Pré Exame Graduação Preta </h5>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>