<?php
	define('RANDNAGEAZUL', 4);
	define('RANDOSSAEAZUL', 3);

	define('RANDNAGEAMARELA', 4);
	define('RANDOSSAEAMARELA', 4);

	define('RANDNAGELARANJA', 8);
	define('RANDOSSAELARANJA', 4);
	define('RANDRENRAKULARANJA', 2);
	define('RANDRENZOKULARANJA', 1);
	define('RANDKAESHILARANJA', 1);

	define('RANDNAGEVERDE', 12);
	define('RANDOSSAEVERDE', 6);
	define('RANDRENRAKUVERDE', 4);
	define('RANDRENZOKUVERDE', 2);
	define('RANDKAESHIVERDE', 3);
	define('RANDSHIMEVERDE', 2);
	define('RANDKANSETSUVERDE', 1);

	define('RANDNAGEROXA', 16);
	define('RANDOSSAEROXA', 6);
	define('RANDRENRAKUROXA', 6);
	define('RANDRENZOKUROXA', 8);
	define('RANDKAESHIROXA', 6);
	define('RANDSHIMEROXA', 4);
	define('RANDKANSETSUROXA', 4);

	define('RANDNAGEMARROM', 20);
	define('RANDOSSAEMARROM', 6);
	define('RANDRENRAKUMARROM', 8);
	define('RANDRENZOKUMARROM', 7);
	define('RANDKAESHIMARROM', 9);
	define('RANDSHIMEMARROM', 6);
	define('RANDKANSETSUMARROM', 8);
?>