<?php 
	require_once('constants.php');
	echo $this->doctype();
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<?php echo $this->headTitle($this->title); ?>
		
		<!-- CSS -->
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>/layout.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>/bootstrap-theme.min.css">
		
		<!-- JS -->
		<script type="text/javascript" src="<?php echo JS; ?>/jquery-1.9.1.js"></script>
		<script type="text/javascript" src="<?php echo JS; ?>/bootstrap.js"></script>
	</head>
	<body>
		<div id="container">
			<header>
				<div id="navigation">
					<nav class="navbar navbar-default" role="navigation">
						<div class="container-fluid">
						    <!-- Brand and toggle get grouped for better mobile display -->
						    <div class="navbar-header">
						      	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						        	<span class="sr-only">Toggle navigation</span>
						        	<span class="icon-bar"></span>
						        	<span class="icon-bar"></span>
						        	<span class="icon-bar"></span>
						      	</button>
						      	<a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/default">
						      		<img src="<?php echo IMG; ?>/dojosyslogoweb.png" id="logo"/>
						      	</a>
						    </div>

						    <!-- Collect the nav links, forms, and other content for toggling -->
						    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						    	<ul class="nav navbar-nav pull-right">
						    		<li><a href="<?php echo $this->baseUrl(); ?>/default">Principal</a>
					    			<li>
				        				<a href="<?php echo $this->baseUrl(); ?>/exame/index">
				        					Exame Graduação
				        				</a>
				        			</li>
						        	<li><a href="#">Sobre</a></li>
						        </ul>
						    </div>
						</div>
					</nav>
				</div>
			</header>
			<section>
				<div id="content">
					<div id="content_fields">
						<?php echo $this->layout()->content ?>
					</div>
				</div>
			</section>
		</div>
	</body>
</html>